version: "3"

services:
  academy-nuxt:
    build:
      context: ./nuxt
      dockerfile: Dockerfile
    container_name: academy-nuxt
    restart: always
    ports:
      - '8010:8000'
  academy-feathers:
    build:
      context: ./feathers
      dockerfile: Dockerfile
    container_name: academy-feathers
    restart: always
    ports:
      - 3010:3010
    env_file:
      - ./feathers/.env
    volumes:
      - './files:/files'